Add publishing GitHub jobs

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Create Release
+name: Release & Publish
 
 on:
   workflow_dispatch:
@@ -12,11 +12,22 @@ on:
 
 permissions:
   contents: write
+  packages: write
 
 jobs:
-  build:
+  checks:
+    name: Requirements
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check user permissions
+        uses: 74th/workflow-permission-action@1.0.0
+        with:
+          users: dedece35,glalloue,jhertout,jules-delecour-dav,olegoaer,zippy1978,utarwyn
+
+  release:
     name: Create release
     runs-on: ubuntu-latest
+    needs: checks
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -28,17 +39,18 @@ jobs:
         with:
           node-version: 18
 
-      - name: Check version
-        run: yarn version check
-
       - name: Apply version
-        run: yarn workspace @ecocode/${{ inputs.linter }} version apply
+        run: yarn version apply
+        working-directory: ${{ inputs.linter }}
 
       - name: Get package version
         id: package-version
         uses: martinbeentjes/npm-get-version-action@main
         with:
           path: ${{ inputs.linter }}
+
+      - name: Check tag non-existence
+        run: if git show-ref --tags --verify --quiet -- "refs/tags/${{ inputs.linter }}/${{ steps.package-version.outputs.current-version }}"; then echo "::error::Tag already exists" && exit 1; fi
 
       - name: Extract release notes
         id: extract-release-notes
@@ -65,3 +77,58 @@ jobs:
           name: ${{ inputs.linter }} ${{ steps.package-version.outputs.current-version }}
           tag_name: ${{ inputs.linter }}/${{ steps.package-version.outputs.current-version }}
           body: ${{ steps.extract-release-notes.outputs.release_notes }}
+
+  publish-npm:
+    runs-on: ubuntu-latest
+    needs: release
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18
+          registry-url: 'https://registry.npmjs.org'
+
+      - name: Install dependencies
+        run: yarn install --immutable
+
+      - name: Copy LICENSE
+        run: cp LICENSE.md ${{ inputs.linter }}/
+
+      - name: Publish package on NPM
+        run: npm publish --access public --workspace ${{ inputs.linter }}
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+  publish-github:
+    runs-on: ubuntu-latest
+    needs: release
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18
+
+      - name: Install dependencies
+        run: yarn install --immutable
+
+      - name: Copy LICENSE
+        run: cp LICENSE.md ${{ inputs.linter }}/
+
+      - name: Add scope to package name
+        run: npx --workspace ${{ inputs.linter }} --yes change-package-name @${{ github.repository_owner }}/ecocode-${{ inputs.linter }}
+
+      - name: Configure GitHub Packages registry
+        uses: bduff9/use-npmrc@v2.0.0
+        with:
+          dot-npmrc: |
+            //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
+            @${{ github.repository_owner }}:registry=https://npm.pkg.github.com
+            always-auth=true
+          working-directory: ${{ inputs.linter }}
+
+      - name: Publish package on GitHub Packages
+        run: npm publish --workspace ${{ inputs.linter }}
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
